- .github/workflows/test.yml
- src/djlint/settings.py
- tests/test_config_gitignore.py
- tox.ini
> Fix gitignore test

- poetry.lock
- pyproject.toml
> Updates PyYAML to 6.0.

- .pre-commit-hooks.yaml
- docs/djlint/usage.rst
This makes the repo a pre-commit hook and provides some predefined hooks for common frameworks.
> Make the repo a pre-commit hook.

- docs/docs/configuration.rst
- src/djlint/settings.py
- src/djlint/src.py
Closes https://github.com/Riverside-Healthcare/djLint/issues/138
> Add Angular profile

- src/djlint/rules.yaml
- tests/test_linter.py
Resolves: https://github.com/Riverside-Healthcare/djLint/issues/156
> Specify acceptable entities

- docs/docs/configuration.rst
- src/djlint/settings.py
- tests/config_custom_html/html.html
- tests/config_custom_html/pyproject.toml
- tests/test_config.py
> [Feature] - allow custom html tags

- docs/src/docs/integrations.md
- docs/src/ru/docs/integrations.md
> add neovim integration

- docs/src/docs/changelog.md
- docs/src/fr/docs/changelog.md
- docs/src/ru/docs/changelog.md
> docs(changelog): update changelog versions

- src/djlint/formatter/expand.py
- src/djlint/formatter/indent.py
- src/djlint/settings.py
- tests/test_html.py
> fix(code tags): fixed indentation on code tags w/ trailing text

- docs/.eleventy.js
- docs/package-lock.json
- docs/package.json
- docs/src/_data/i18n/index.js
- docs/src/_includes/docs_layout.njk
- docs/src/_includes/foot.njk
- docs/src/_utils/styles.11ty.js
- docs/src/docs/docs.json
- renovate.json
> docs(edit): added edit on github link

- .github/pull_request_template.md
- docs/src/docs/configuration.md
- docs/src/fr/docs/configuration.md
- docs/src/ru/docs/configuration.md
- src/djlint/__init__.py
- src/djlint/formatter/condense.py
- src/djlint/formatter/indent.py
- src/djlint/rules.yaml
- src/djlint/settings.py
- tests/test_config/test_preserve_blank_lines/html.html
- tests/test_config/test_preserve_blank_lines/test_config.py
- tests/test_linter/test_linter.py
Closes #270# Pull Request Check List
> fix(h025): fixes rule H025 where tags have curly hash

- .github/workflows/release.yml
> added token

- docs/src/_includes/index.njk
- package.json
- poetry.lock
- pyproject.toml
- requirements.txt
> docs(contributing): updated contributing docs, moved in dev deps

- docs/src/_data/configuration.json
- src/djlint/formatter/condense.py
- src/djlint/settings.py
- tests/test_config/test_blank_lines_before_tag/html.html
- tests/test_config/test_blank_lines_before_tag/html_eight.html
- tests/test_config/test_blank_lines_before_tag/html_five.html
- tests/test_config/test_blank_lines_before_tag/html_four.html
- tests/test_config/test_blank_lines_before_tag/html_seven.html
- tests/test_config/test_blank_lines_before_tag/html_six.html
- tests/test_config/test_blank_lines_before_tag/html_three.html
- tests/test_config/test_blank_lines_before_tag/html_two.html
- tests/test_config/test_blank_lines_before_tag/pyproject.toml
- tests/test_config/test_blank_lines_before_tag/test_config.py
> feat(formatter): added option to add blank line before tags

- bin/index.js
- docs/src/_data/configuration.json
- docs/src/docs/formatter.md
- docs/src/docs/getting-started.md
- docs/src/fr/docs/formatter.md
- docs/src/fr/docs/getting-started.md
- docs/src/ru/docs/formatter.md
- docs/src/ru/docs/getting-started.md
- poetry.lock
- pyproject.toml
- src/djlint/__init__.py
- src/djlint/formatter/css.py
- src/djlint/formatter/js.py
- src/djlint/reformat.py
- src/djlint/settings.py
- tests/test_config/test_scripts_styles/html.html
- tests/test_config/test_scripts_styles/pyproject.toml
- tests/test_config/test_scripts_styles/test_config.py
> feat(formatter): added options to format css and js using jsbeautifier

- .github/workflows/lint.yml
- docs/src/docs/changelog.md
- docs/src/docs/integrations.md
- package.json
- poetry.lock
- pyproject.toml
- requirements.txt
- src/djlint/__init__.py
- src/djlint/formatter/condense.py
- src/djlint/formatter/css.py
- src/djlint/formatter/expand.py
- src/djlint/formatter/js.py
- src/djlint/settings.py
- tests/test_html/test_attributes.py
- tox.ini
> Fix spelling

- docs/src/_includes/layout.njk
> docs(docs): added meta tag

- package.json
- pyproject.toml
- src/djlint/formatter/attributes.py
- tests/test_html/test_attributes.py
solves issue with boolean attributes at the start of tags.
closes #290
Resolves: #290
> fix(formatter): fix IndexError while adding indentation to attributes

- docs/src/docs/integrations.md
- docs/src/fr/docs/integrations.md
- docs/src/ru/docs/integrations.md
- requirements.txt
- src/djlint/rules.yaml
- tests/test_linter/test_linter.py
> feat(linter): updated rule 18 to allow "tel:"

- .github/ISSUE_TEMPLATE/linter_bug_report.md
- poetry.lock
- pyproject.toml
- requirements.txt
- src/djlint/formatter/css.py
- src/djlint/formatter/js.py
- tests/test_config/test_scripts_styles/ignore.html
- tests/test_config/test_scripts_styles/test_config.py
> fix(js formatting): added support for jsbeautify ignore blocks

- src/djlint/formatter/indent.py
- tests/test_html/test_tag_span.py
> fix(span): fixed indent on nested inline tags on a span

- src/djlint/output.py
> feat(stats): moved linter stats to be appended to lint output

- docs/src/_includes/foot.njk
- docs/src/_includes/index.njk
- docs/src/_includes/layout.njk
- docs/src/_includes/nav.njk
- docs/src/static/css/site.scss
- src/djlint/formatter/condense.py
- tests/test_config/test_blank_lines_after_tag/html_ten.html
- tests/test_config/test_blank_lines_after_tag/test_config.py
- tests/test_config/test_blank_lines_before_tag/test_config.py
> fix(formatter): fixed issue with blank links added between blocks

- .flake8
- package.json
- pyproject.toml
`flake8` is not yet compatible with `pyproject.toml` but `mypy` and most other tools are.
> Move mypy config into pyproject.toml

- .github/workflows/cancel.yml
- .pre-commit-config.yaml
- docs/package-lock.json
- docs/package.json
- src/djlint/formatter/indent.py
- src/djlint/settings.py
- tests/test_html/test_tag_span.py
> chore(deps) Update dependency eslint to v8.26.0

- src/djlint/settings.py
- tests/test_html/test_alpinejs.py
> fix(formatter): fixed a few broken alpinejs attributes

- docs/src/docs/languages/django.md
- docs/src/docs/languages/jinja.md
- docs/src/docs/languages/nunjucks.md
- docs/src/docs/languages/twig.md
> fixed compare urls

- build_demo.sh
- docs/src/static/js/worker.js
> fix(docs): fixed doc build

- src/djlint/formatter/indent.py
- tests/conftest.py
- tests/test_handlebars/test_each.py
- tests/test_jinja/test_parenthesis.py
> fix(formatter): fixed template tag formatting with trailing parenthesis

- .github/workflows/demo.yml
- docs/src/docs/languages/twig.md
- src/djlint/formatter/compress.py
- src/djlint/settings.py
- tests/test_html/test_doctype_declarations.py
> docs(twig): added twig example

- docs/src/_data/configuration.json
- docs/src/_includes/nav.njk
- docs/src/docs/getting-started.md
- docs/src/fr/docs/getting-started.md
- docs/src/ru/docs/getting-started.md
- src/djlint/__init__.py
- src/djlint/settings.py
- tests/conftest.py
- tests/test_config/test_ignore_blocks.py
> chore(demo): updated demo analytics events

- src/djlint/formatter/indent.py
- src/djlint/rules.yaml
- tests/test_linter/test_django_linter.py
- tests/test_linter/test_h037.py
- tests/test_nunjucks/test_set.py
> fix(formatter): fixed set_ tags being broken

- .github/workflows/release.yml
> ci(release): added npm install to release

- docs/src/docs/integrations.md
> docs(urls): update neovim plugin urls and organize repeated titles
