djlint/djLint

docs/djlint/usage.rst, src/djlint/__init__.py, tests/test_djlint.py
I thought it would be useful to have a `--version` option
=> feat: Add `--version` option

README.md
from `https://djlint.readthedocs.io` to `https://djlint.com/` 😇
=> fix: broken link "djlint documentation" in README

src/djlint/settings.py, tests/test_html.py
The source element does not permit content therefore subsequent tags shouldn't be indented, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source
=> Do not indent the <source> element, it does not permit content

docs/djlint/configuration.rst, docs/djlint/usage.rst, src/djlint/__init__.py
This is an adjustment due to rule name related changes in `v0.4.5`.
If you prefer a different rule name, please change it.
=> chore: adjust docs and help for rule name changes

docs/src/docs/integrations.md
I am happy to inform you that there is now a `djLint` extension for Visual Studio Code.
Resolves: #145
=> Add Visual Studio Code to integrations.md

src/djlint/__init__.py
djlint is invoked with `__name__ == "djlint"` (it must be, or the relative imports would fail), so the `if __name__ == "__main__"` block does nothing. These calls need to be made from `main()` itself.
The `colorama_text` decorator makes this easy.
=> Correctly initialize and deinitialize colorama

poetry.lock, pyproject.toml, requirements.txt, src/djlint/settings.py
Tomli is the upcoming python 3.11 standard library toml parser,
and will be available as tomllib when 3.11 releases.
This switches from using tomlkit to tomli, which brings it inline
with black, poetry, and many other toml parsing python packages
=> Switch from tomlkit to tomli

src/djlint/rules.yaml, tests/test_linter/test_linter.py
Avoids matching
```
<div x-id-y
<div id-y
<div x-id
```
etc.
Resolves: #281
=> Update H026 regex to ignore hyphens before and after class/id

bin/index.js, renovate.json
I noticed syntax error when trying to run `djlint` binary installed with `npm`.
Just looked at the code and found that it was a node.js file used as a binary but without a shebang, so my system was not able to run it.
I tested locally, it fixes my issue.
Let me know if it's good for you!
Resolves: no issue
=> adds missing shebang in node binary

docs/src/docs/integrations.md, docs/src/fr/docs/integrations.md, docs/src/ru/docs/integrations.md
I also edited the translations a bit, because Visual Studio Marketplace is a proper name, so I don't think you need to translate it.
=> Add a link to the djlint-vscode page on Open VSX

src/djlint/rules.yaml, tests/test_linter/test_linter.py
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs
This PR allow `"data:"` links without `"{% url "` pattern. 
It also fixes tests for "mailto:" and "tel:" that didn't use a profile and passed even without the correct rule.
Example:
```html
<a href="data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==">Text link</a>
```
=> Allow data: for links.

docs/src/docs/integrations.md, docs/src/fr/docs/integrations.md, docs/src/ru/docs/integrations.md
Resolves: #undefined
- [ x] Updated **documentation** for changed code.
Document the additional extensions that pre-commit will use when specifying `types_or: [jinja]` in the hook config. I actually got confused by the current doc, thinking it would only consider .j2 
pre-commit uses 'identity' to identify file extensions, for jinja the list of extensions can be seen  [here](https://github.com/pre-commit/identify/blob/main/identify/extensions.py#L107)
Thanks for the library btw, pretty cool!
=> Document the additional extensions considered by pre-commit for jinja

src/djlint/formatter/css.py, src/djlint/formatter/expand.py, src/djlint/formatter/js.py, src/djlint/rules.yaml, src/djlint/settings.py, tests/test_config/test_format_css.py, tests/test_config/test_format_js.py, tests/test_django/test_blocktrans.py, tests/test_django/test_blocktrans_trimmed.py, tests/test_django/test_quoted.py, tests/test_linter/test_h005.py, tests/test_linter/test_h006.py, tests/test_linter/test_h007.py, tests/test_linter/test_h008.py, tests/test_linter/test_h009.py, tests/test_linter/test_h010.py, tests/test_linter/test_h037.py, tests/test_linter/test_linter.py
they will now be ignored. Thanks @davidbgk, @Benik3
closes #613
they will now be ignored. Thanks @davidbgk, @Benik3
closes #613
=> fix(formatter): fixed js/css being formatted even inside ignored blocks

src/djlint/settings.py, tests/test_config/test_custom_blocks.py, tests/test_config/test_djlintrc/test_config.py, tests/test_config/test_djlintrc_custom/test_config.py, tests/test_config/test_pyproject/test_config.py
If you define a custom block of `new_thing` but have a tag in your code `{% new_thing_2 %}` the current code will apply the custom blocks logic to `new_thing_2` even though it's not specified in the `custom_blocks` setting.
Adding a negative lookahead to the tags in the regex so that it only matches EXACT matches.
=> Defining custom blocks isn't strict enough

src/djlint/formatter/indent.py, tests/test_nunjucks/test_filters.py, tests/test_nunjucks/test_functions.py
This update reverts the formatting on of chained functions as it broke filter strings, but at the same time leaves in a fix for extra spaces that the original issue found.
re #720, #704
=> fix(formatter): reverted chained function formatting

src/djlint/settings.py
Resolves: #767 
It removes an unnecessary `return` statement. It's strange how such an error could be made in #759, because even **PyCharm** warns about this `return` :sweat_smile:
=> Fix `.djlintrc` config loading

src/djlint/rules/H025.py, tests/test_linter/test_linter.py
I couldn't see any reason to keep orphaned closing tags in `open_tags` so store them separately to avoid accidental matches against subsequent closing tags.
Resolves: #786
=> Fix missed H025 for double closing HTML tags

src/djlint/reformat.py, tests/test_djlint/test_djlint.py
We use djLint as part of [treefmt][1] to reformat HTML templates tree-wide, and treefmt [looks][2] at file modification time to determine if it was reformatted or not. And with `--fail-on-change` option passed, it exits with status 1 when it thinks files are modified.
This patch makes djLint not rewrite the file if there are no changes to write back, which makes `treefmt --fail-on-change` do the right thing.
[1]: https://github.com/numtide/treefmt
[2]: https://github.com/numtide/treefmt/blob/v0.6.1/src/engine.rs#L278
=> fix(formatter): Avoid rewriting the file if it has not been changed

pyproject.toml
This makes it easier for linux distro maintainers to import the list of dependencies into their packaging formats, e.g. https://build.opensuse.org/package/show/home:jayvdb:py-new/python-djlint
I have left `python` entry at the top, as it isnt the same as the others
=> Sort pyproject.toml dependencies

src/djlint/rules.yaml, tests/test_linter/test_linter.py
From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title:
> This element only includes the global attributes.
I picked those that seemed reasonable from
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#list_of_global_attributes
=> fix(H016): Allow attributes on <title>

src/djlint/rules.yaml, tests/test_linter/test_django_linter.py
=> Adding test and ignore for sms links

src/djlint/formatter/condense.py, src/djlint/settings.py, tests/test_config/test_preserve_blank_lines.py
Resolves: #812 
It wasn't detecting tabs as a valid whitespace between HTML tags, causing it to transform:
`<div>\n\t<p></p>\n</div>`
into:
`<div>\n\t\n<p></p>\n</div>`
Notice that the transformed text has an extra new line after the tab character. Normally extra new lines are removed, but with `--preserve-blank-lines`, this extra new line persists.
Note:
- `--preserve-blank-lines` and `--max-blank-lines` are incompatible with each other (I think this was true before my PR). Since `--max-blank-lines` preserves blank lines as well, it would make a lot of sense to combine the two options into one.
=> Fix: not detecting tabs as a valid seperation between tags.

src/djlint/formatter/indent.py, tests/test_config/test_max_attribute_length.py
=> fix: max attribute length with longer regex custom html tags

djlint/helpers.py
If a file is formatted, the code attempts to extract the ignored blocks or unformatted blocks several times from the same HTML string.
This commit adds a cache for the unique combination `sha256(html || config.REGEX)`. It stores the results as `[(begin,end)]`, as it seems like the accessing `.start()` or `.end()` is somewhat costly. (Same applies for the match that is given as argument)
I used https://github.com/netbox-community/netbox for testing. In the `netbox` directory there are two subdirectories with templates: `templates` and `utilities`.
I cloned it twice:
```
/tmp/diff
old/ <- For upstream master of djlint
new/ <- For my changes
```
The outputs of `git diff HEAD~1` are identical
To test I used:
```
pip uninstall djlint -y; pip install djlint
cd /tmp/diff/old/netbox
time djlint …
```
=> fix: Cache some results of re.finditer

djlint/helpers.py
I only modified the hot functions, but can modify all to use for loops if you want. See #986 for more information.
Before:
After:
Performance numbers:
Netbox, parallel: 3.7-3.8s
EDX platform, parallel: 25s
As you can see, most of the time is now spent compiling/looking up regex in the caches (Addressed by Performance Improvement 5)
I will wait with Performance Improvement 4 and 5 until the first three are merged.
=> Performance Improvement 3 - Refactor some any()s to for loops

djlint/formatter/indent.py
`is_ignored_block_opening(config, item)` and `is_safe_closing_tag(config, item)` are each called multiple times in indent.py with the same parameters. This can be deduplicated.
(Note I've changed the block `with executor_cls(max_workers=worker_count) as exe:` in `__init__.py` to be serial to make the profiler work.
```python
for this_file in file_list:
file_errors.append(process(config, this_file))
```
is_ignored_block_opening (With children): 12.4% of all the time, 61562x calls
is_safe_closing_tag (With children): 6.24% of all the time, 33139x calls
Concrete data:
```
Netbox with serial execution (Patch above): 9.7s
Netbox with unchanged __init__.py              :    4s
OpenEDX platform                                           : 33s
```
is_ignored_block_opening (With children): 4.73% of …
=> Performance Improvement 1 - Reduce number of pure calls.

djlint/formatter/attributes.py, djlint/formatter/compress.py, djlint/formatter/condense.py, djlint/formatter/css.py, djlint/formatter/expand.py, djlint/formatter/indent.py, djlint/formatter/js.py, djlint/helpers.py, djlint/lint.py, djlint/rules/H025.py, djlint/src.py
See #986 for details.
The problem is, that each OR of the enum flags is extremely expensive for some reason.
You can see that, the `enum.__or__` is called 975773x times for Netbox (That's the base repo I use for measurements) and takes 9.58% of the entire runtime.
After this patch, `enum.__or__` is called only 30768x times. This is outside of the graph rendered by gprof2dot, so here you have a screenshot from snakeviz :)
New numbers: (Without the perf-1 branch applied), small but nevertheless somewhat impactful.
Netbox, parallel: 3.8s
EDX platform: 31s
=>  Performance Improvement 2 - Deduplicate regex flags

djlint/helpers.py, djlint/settings.py
Resolves: No issue, since only performance improvements
Neither are necessary, since again, only performance improvements.
This adds a simple check for unformatted blocks (djlint:off blocks) before using the quite expensive proper ones.
As @JCWasmx86 suggested in his last PR, djlint spends a lot of time on those unformatted block checks.
I couldn't figure out a more elaborate solution without making it really complicated, but for most projects (those without lots of djlint:off blocks) this will basically yield perfect results.
As common in @JCWasmx86 PRs, I used [edx-platform repo](https://github.com/openedx/edx-platform) as a benchmark (average of 10 runs, all files in the repo):
1. Current master (1.36.0): 6.7s
2. This PR: 1.45s
=> perf: simple skip for unformatted blocks

djlint/settings.py, djlint/src.py, tests/test_config/test_excludes/pyproject.toml
Closes https://github.com/djlint/djLint/issues/1028
🛠️ with ❤️ by [Siemens](https://opensource.siemens.com/)
/cc @nejch
=> fix(src): resolve exclude paths

djlint/formatter/expand.py, djlint/settings.py, tests/test_django/test_templatetag_ext.py
Resolves: #1052
(no real need to update docs)
This is a quick fix.
Overall I think djlint should be refactored in some regards. 
Many regexes (like this one I modified) should be using existing basic regexes as building blocks more I think.
Many regexes don't respect nesting of brackets and escaping properly (again, like this one here), and do not respect the differences between what e.g. an attribute key or value. 
Both these issues rarely matter, but I could definitely construct valid django templates where they do. Not super easy to fix/refactor, so I'm currently trying to cover some ground with these smaller issues/PRs and get some tests for all of my use cases, so I'm maybe confident enough to refactor some stuff later.
=> fix #1052: template tag inside template tag

djlint/__init__.py, docs/src/_includes/cli.md
This pull request includes minor corrections to typos in the documentation and code comments. The changes ensure that the word "becomse" is corrected to "becomes" in both the `djlint/__init__.py` file and the CLI documentation.
Typos corrected:
* [`djlint/__init__.py`](diffhunk://#diff-97803ad82bc8d3a30af27492e3964bf85ec83ee7d0f1fda67fb8034442e8c2d2L224-R224): Fixed typo in the help message for the `--close-void-tags` option.
* [`docs/src/_includes/cli.md`](diffhunk://#diff-83d9d38adbb496c8416991649acc4556082f14eb9a544bcd15d05c7f00dc7a5cL58-R58): Corrected the same typo in the CLI documentation under the `Options:` section.
- ~~[ ] Added **tests** for changed code.~~ (Tho I'm a TDD myself, I don't think tests are necessary for this)
=> [doc] fix: Correct typo in CLI help text

src/djlint/formatter/indent.py, tests/test_html/test_hyperscript.py
=> Fix formatting on "/>" in HTML attributes

src/djlint/settings.py, tests/test_handlebars/test_unless.py
The unless tag `{{#unless}} {{/unless}}` was not seen as a template tag. 
I fixed it by adding it to the template tags config.
Resolves: #972
I don't think a documentation change is needed because handlebars supports unless but djlint didn't before this commit.
=> Fix: indentation for handlebars unless
